# Thomas Hazekamp, 20423602, Operating Systems Assignment 1, CA216
# I have read and understood DCU's Academic Integrity Policy, I have given detailed reference to the authors of any material used to help with this project.

# Combining the three c files and placing the executable in the bin directory of the parent folder
myshell: myshell.c int-commands.c utilities.c
	gcc myshell.c int-commands.c utilities.c -o ../bin/myshell